# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: kuadrant-addon-controller
#   labels:
#     app: kuadrant-addon-controller
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kuadrant-addon-controller
#   template:
#     metadata:
#       labels:
#         app: kuadrant-addon-controller
#     spec:
#       serviceAccountName: kuadrant-addon-sa
#       containers:
#       - name: kuadrant-addon-controller
#         image: quay.io/open-cluster-management/addon-examples
#         imagePullPolicy: IfNotPresent
#         args:
#           - "/kuadrant"