{
 "title": "Stitch: Gatekeeper",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Violations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of violations",
   "type": "timeseries",
   "description": "Total number of audited violations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(gatekeeper_violations) by(enforcement_action)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current number of violations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_violations) by (enforcement_action)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current violations ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "opa_scorecard_violations", "legendFormat": "__auto" }
   ]
  },
  { "title": "Constraints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of known constraints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(1,sum (gatekeeper_constraints{status=\"active\"}) by (pod))",
     "legendFormat": "Active"
    },
    {
     "expr": "topk(1,sum (gatekeeper_constraints{status=\"error\"}) by (pod))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Current known constraints",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "expr": "count(label_replace( apiserver_storage_list_total{resource=~\".*\\\\.constraints\\\\.gatekeeper\\\\.sh\"},\n    \"resource\",\n    \"$1\",\n    \"resource\",\n    \"(.*)\\\\.constraints\\\\.gatekeeper\\\\.sh\"\n  )) by (resource)",
     "legendFormat": "Active"
    }
   ]
  },
  { "title": "Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Number of requests that are routed to validation webhook",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": " (rate(gatekeeper_validation_request_count{admission_status=\"allow\"}[20m]))",
     "legendFormat": "Status={{admission_status }} Pod={{pod}}"
    },
    {
     "expr": " (rate(gatekeeper_validation_request_count{admission_status=\"error\"}[20m]))",
     "legendFormat": "Status={{admission_status }} Pod={{pod}}"
    }
   ]
  },
  {
   "title": "Number of requests that are routed to mutation webhook",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": " (rate(gatekeeper_mutation_request_count[20m]))",
     "legendFormat": "Status= {{mutation_status}} Pod= {{pod}}"
    }
   ]
  },
  { "title": "Auditing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Time since last Audit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - gatekeeper_audit_last_run_time"
    }
   ]
  },
  {
   "title": "Audit Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gatekeeper_audit_duration_seconds_count[10m])"
    }
   ]
  },
  {
   "title": "Current number of GVK being watched",
   "type": "stat",
   "description": "Group version kind being watch",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,gatekeeper_watch_manager_watched_gvk)"
    }
   ]
  }
 ]
}