{
 "title": "Stitch: Platform Engineer Dashboard",
 "description": "Stitch APIs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Gateways and Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Total Gateways with an Accepted state of True",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{type=\"Accepted\"} > 0)"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 1 },
   "targets": [
    { "expr": "gatewayapi_gateway_info" },
    {
     "expr": "gatewayapi_gateway_status{type=\"Programmed\"}"
    },
    {
     "expr": "gatewayapi_gateway_status{type=\"Accepted\"}"
    }
   ]
  },
  {
   "title": "Programmed",
   "type": "stat",
   "description": "Total Gateways with a Programmed state of True",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{type=\"Programmed\"} > 0)"
    }
   ]
  },
  {
   "title": "Gateway Policies",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gatewayapi_tlspolicy_target_info{target_kind=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_ratelimitpolicy_target_info{target_kind=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_authpolicy_target_info{target_kind=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_dnspolicy_target_info{target_kind=\"Gateway\"}"
    }
   ]
  },
  {
   "title": "Route Policies",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "gatewayapi_tlspolicy_target_info{target_kind!=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_ratelimitpolicy_target_info{target_kind!=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_authpolicy_target_info{target_kind!=\"Gateway\"}"
    },
    {
     "expr": "gatewayapi_dnspolicy_target_info{target_kind!=\"Gateway\"}"
    }
   ]
  },
  { "title": "Constraints and Violations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current number of violations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatekeeper_violations{enforcement_action=~\"(warn|deny)\"}) by (enforcement_action)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current violations ",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 14 },
   "targets": [
    { "expr": "opa_scorecard_violations", "legendFormat": "__auto" }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "APIs",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "gatewayapi_httproute_hostname_info{}",
     "legendFormat": "__auto"
    },
    { "expr": "gatewayapi_httproute_labels{}" }
   ]
  },
  {
   "title": "API Traffic Summary (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[5m])) by (destination_workload) * on(destination_workload) group_right label_replace(gatewayapi_httproute_labels{}, \"destination_workload\", \"$1\",\"deployment\", \"(.+)\")",
     "legendFormat": "API: {{name}}"
    }
   ]
  }
 ]
}