apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2023-11-20T13:08:29Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: multicluster-gateway-controller.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DNSHealthCheckProbe
      name: dnshealthcheckprobes.kuadrant.io
      version: v1alpha1
    - kind: DNSPolicy
      name: dnspolicies.kuadrant.io
      version: v1alpha1
    - kind: DNSRecord
      name: dnsrecords.kuadrant.io
      version: v1alpha1
    - description: ManagedZone is the Schema for the managedzones API
      displayName: Managed Zone
      kind: ManagedZone
      name: managedzones.kuadrant.io
      version: v1alpha1
    - kind: TLSPolicy
      name: tlspolicies.kuadrant.io
      version: v1alpha1
  description: multi-cluster gateway controller, manages multi-cluster gateways based
    on gateway api and policy attachment
  displayName: Multicluster-gateway-controller
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - events
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
          - deletecollection
          - patch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - get
          - create
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          - certificatesigningrequests/approval
          verbs:
          - get
          - list
          - watch
          - create
          - update
        - apiGroups:
          - certificates.k8s.io
          resources:
          - signers
          verbs:
          - approve
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - managedclusters
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - work.open-cluster-management.io
          resources:
          - manifestworks
          verbs:
          - create
          - update
          - get
          - list
          - watch
          - delete
          - deletecollection
          - patch
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - managedclusteraddons/finalizers
          verbs:
          - update
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - clustermanagementaddons/finalizers
          verbs:
          - update
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - clustermanagementaddons
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - managedclusteraddons
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - managedclusteraddons/status
          verbs:
          - update
          - patch
        - apiGroups:
          - kuadrant.io/v1beta1
          resources:
          - kuadrant
          verbs:
          - get
          - list
          - watch
          - create
          - update
        serviceAccountName: mgc-add-on-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - placementdecisions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - authpolicies
          - ratelimitpolicies
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - work.open-cluster-management.io
          resources:
          - manifestworks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: mgc-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - clusterissuers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - issuers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - managedclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnspolicies
          verbs:
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - dnspolicies/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnspolicies/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - tlspolicies
          verbs:
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - tlspolicies/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - tlspolicies/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: mgc-policy-controller
      deployments:
      - label:
          control-plane: kuadrant-add-on-manager
        name: mgc-add-on-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: kuadrant-add-on-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: controller
              labels:
                control-plane: kuadrant-add-on-manager
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /add-on-manager
                envFrom:
                - configMapRef:
                    name: controller-config
                    optional: true
                image: quay.io/kuadrant/addon-manager:main
                imagePullPolicy: Always
                name: controller
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mgc-add-on-manager
              terminationGracePeriodSeconds: 10
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: multicluster-gateway-controller
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: kuadrant
          control-plane: controller-manager
        name: mgc-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=0.0.0.0:8080
                - --leader-elect
                command:
                - /controller
                image: quay.io/kuadrant/multicluster-gateway-controller:main
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 8080
                  name: metrics
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 256Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mgc-controller-manager
              terminationGracePeriodSeconds: 10
      - label:
          control-plane: policy-controller
        name: mgc-policy-controller
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: policy-controller
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: policy-controller
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /policy_controller
                image: quay.io/kuadrant/policy-controller:main
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: policy-controller
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 256Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: mgc-policy-controller
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: mgc-controller-manager
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: mgc-policy-controller
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Gateway-API
  - DNS
  - Global-Load-Balancing
  - Multi-Cloud
  links:
  - name: Multicluster Gateway Controller
    url: https://multicluster-gateway-controller.domain
  maintainers:
  - email: hcg-team@redhat.com
    name: HCG-Team
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/Kuadrant/multicluster-gateway-controller
  version: 0.0.0
