apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2024-02-04T15:48:27Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: multicluster-gateway-controller.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: multi-cluster gateway controller, manages multi-cluster gateways based
    on gateway api and policy attachment
  displayName: Multicluster-gateway-controller
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Gateway-API
  - DNS
  - Global-Load-Balancing
  - Multi-Cloud
  links:
  - name: Multicluster Gateway Controller
    url: https://multicluster-gateway-controller.domain
  maintainers:
  - email: hcg-team@redhat.com
    name: HCG-Team
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/Kuadrant/multicluster-gateway-controller
  version: 0.0.0
