# permissions for end users to view managedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedzone-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones/status
  verbs:
  - get
