# permissions for end users to edit managedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedzone-editor-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones/status
  verbs:
  - get
