# permissions for end users to edit tlspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlspolicy-editor-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies/status
  verbs:
  - get
