# permissions for end users to view tlspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlspolicy-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies/status
  verbs:
  - get
