apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    version: 6.12.1
    releaseName: mctc
    namespace: external-dns
    valuesInline:
      provider: aws
      aws:
        zoneType: public
      sources:
        - crd
      logLevel: debug
      # annotationFilter: type=global
      crd:
        create: true
      policy: sync
      registry: txt
      txtPrefix: mctc-
