apiVersion: kuadrant.io/v1alpha1
kind: ManagedZone
metadata:
  name: test1.mn.google.hcpapps.net
spec:
  domainName: test1.mn.google.hcpapps.net
  description: "test1.mn.google.hcpapps.net managed domain"
  dnsProviderSecretRef:
    name: mgc-google-credentials
    namespace: multi-cluster-gateways
    type: Google
  parentManagedZone:
    name: mn.google.hcpapps.net
