apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: etcd
    repo: https://charts.bitnami.com/bitnami
    releaseName: mgc
    valuesInline:
      auth:
        rbac:
          create: false
          allowNoneAuthentication: true
      service:
        type: ClusterIP
        enabled: true
        clusterIP: "100.9.125.73"
