apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: policy-controller
  name: policy-controller-metrics
  namespace: system
spec:
  selector:
    control-plane: policy-controller
  ports:
    - protocol: TCP
      name: metrics
      port: 8080
      targetPort: metrics