# permissions for end users to view tlspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tlspolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tmp
    app.kubernetes.io/part-of: tmp
    app.kubernetes.io/managed-by: kustomize
  name: tlspolicy-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies/status
  verbs:
  - get
