kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuadrant-addon-controller
  namespace: ocm-addon-manager
  labels:
    app: kuadrant-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuadrant-addon-controller
  template:
    metadata:
      labels:
        app: kuadrant-addon-controller
    spec:
      serviceAccountName: kuadrant-addon-sa
      containers:
      - name: kuadrant-addon-controller
        image: ocm:v1.0.0
        imagePullPolicy: IfNotPresent
        