namespace: multi-cluster-gateways

namePrefix: mgc-

resources:
  - managed_zone.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: controller-config
  envs:
    - ../../../../controller-config.env

secretGenerator:
  - name: gcp-credentials
    envs:
      - ../../../../gcp-credentials.env
    type: "kuadrant.io/gcp"

replacements:
  - source:
      kind: ConfigMap
      name: controller-config
      version: v1
      fieldPath: data.ZONE_NAME
    targets:
      - select:
          kind: ManagedZone
          name: mgc-dev-mz-gcp
        fieldPaths:
          - spec.id
  - source:
      kind: ConfigMap
      name: controller-config
      version: v1
      fieldPath: data.ZONE_DNS_NAME
    targets:
      - select:
          kind: ManagedZone
          name: mgc-dev-mz-gcp
        fieldPaths:
          - spec.domainName
 
        
