namespace: multi-cluster-gateways

namePrefix: mgc-

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: gcp-credentials
    envs:
      - ../../../../gcp-credentials.env
    type: "kuadrant.io/gcp"
