apiVersion: kuadrant.io/v1alpha2
kind: DNSPolicy
metadata:
  name: example-dnspolicy
spec:
  targetRef:
    name: example-gateway
    group: ""
    kind: Gateway
  healthCheck:
    endpoint: /
    protocol: HTTP
  