apiVersion: kuadrant.io/v1alpha2
kind: DNSRecord
metadata:
  name: dnsrecord-ns
spec:
  providerRef:
    name: managedzone-sample
    kind: ManagedZone
  endpoints:
    - dnsName: testns.hcpapps.net
      recordTTL: 172800
      recordType: NS
      targets:
        - ns-59.awsdns-07.com
        - ns-59.awsdns-07.com
        - ns-910.awsdns-49.net
        - ns-1440.awsdns-52.org
