apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: dnsrecord-ns
    app.kubernetes.io/instance: dnsrecord-sample
    app.kubernetes.io/part-of: multicluster-gateway-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: multicluster-gateway-controller
  name: dnsrecord-ns
spec:
  managedZone:
    name: mgc-dev-mz-aws
  endpoints:
    - dnsName: testns.hcpapps.net
      recordTTL: 172800
      recordType: NS
      targets:
        - ns-59.awsdns-07.com
        - ns-59.awsdns-07.com
        - ns-910.awsdns-49.net
        - ns-1440.awsdns-52.org
