apiVersion: kuadrant.io/v1alpha2
kind: ManagedZone
metadata:
  name: managedzone-sample
spec:
  domainName: testmz.hcapps.net
  description: "My managed domain"
  providerRef:
    name: my-provider-credentials
    kind: Secret