apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    region: us-east-1
    country: us
  name: cluster1
stringData:
  name: cluster1
  server: https://127.0.0.1:64094
  config: |
    {
      "tlsClientConfig": {
        "insecure": true,
        "caData": "test",
        "certData": "test",
        "keyData": "test"
      }
    }