apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../namespace.yaml
helmGlobals:
  chartHome: ../charts
helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    version: 6.19.1
    releaseName: mctc
    valuesInline:
      #ToDo This chart doesn't support adding these as required.
      #extraArgs:
        #managed-record-types: "A"
        #managed-record-types: "CNAME"
        #managed-record-types: "NS"
      interval: "20s"
      image:
        registry: quay.io
        repository: kuadrant/external-dns
        tag: v0.13.4-dirty-amd64
      domainFilters:
       - google.hcpapps.net
      provider: google
      google:
        project: "it-cloud-gcp-rd-midd-san"
        serviceAccountSecret: "mctc-external-dns-google-creds"
      sources:
        - crd
      logLevel: debug
      crd:
        create: false
        apiversion: "kuadrant.io/v1alpha1"
        kind: "DNSRecord"
      policy: sync
      registry: txt
      txtPrefix: mctc-

secretGenerator:
  - name: mctc-external-dns-google-creds
    files:
      - credentials.json
    options:
      disableNameSuffixHash: true

