namespace: multi-cluster-gateways

namePrefix: mgc-

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: aws-credentials
    envs:
      - ../../../../aws-credentials.env
    type: "kuadrant.io/aws"
