namespace: multi-cluster-gateways

namePrefix: mgc-

resources:
  - namespace.yaml
  - managed_zone.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: controller-config
    envs:
      - ../../../controller-config.env

secretGenerator:
  - name: aws-credentials
    envs:
      - ../../../../aws-credentials.env
    type: "kuadrant.io/aws"

replacements:
  - source:
      kind: ConfigMap
      name: controller-config
      version: v1
      fieldPath: data.AWS_DNS_PUBLIC_ZONE_ID
    targets:
      - select:
          kind: ManagedZone
          name: mgc-dev-mz
        fieldPaths:
          - spec.id
  - source:
      kind: ConfigMap
      name: controller-config
      version: v1
      fieldPath: data.ZONE_ROOT_DOMAIN
    targets:
      - select:
          kind: ManagedZone
          name: mgc-dev-mz
        fieldPaths:
          - spec.domainName
