kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuadrant-olm
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["operatorgroups"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["kuadrant.io/v1beta1"]
  resources: ["kuadrant"]
  verbs: ["get", "list", "watch", "create", "update"]
