apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: authpolicy-mutation
spec:
  applyTo:
  - groups: ["kuadrant.io"]
    kinds: ["AuthPolicy"]
    versions: ["v1beta2"]
  match:
    kinds:
    - apiGroups: ["*"]
      kinds: ["AuthPolicy"]
  location: "spec.rules"
  parameters:
    assign:
      value: 
        authentication:
          "keycloak-users":
            jwt:
              issuerUrl: https://keycloak-rhsso.apps.stitchpoc1.cdnq.p1.openshiftapps.com/auth/realms/kuadrant