# Local deployment overlay.
#
# Set the deployment imagePullPolicy to Never. This is required if you are using a local image loaded into kind i.e. make kind-load-policy-controller
#

resources:
  - ../../default

patchesStrategicMerge:
- manager_config_patch.yaml
