apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-controller
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: policy-controller
        imagePullPolicy: Never
