apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: etcd
    repo: https://charts.bitnami.com/bitnami
    releaseName: mctc
    valuesInline:
      auth:
        rbac:
          create: false
          allowNoneAuthentication: true
      service:
        type: ClusterIP
        enabled: true
        clusterIP: "10.96.125.73"
