apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-monitor
  namespace: gatekeeper-system
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      gatekeeper.sh/system: 'yes'