# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/kuadrant.io_dnsrecords.yaml
- bases/kuadrant.io_dnspolicies.yaml
- bases/kuadrant.io_managedzones.yaml
- bases/kuadrant.io_dnshealthcheckprobes.yaml
- bases/kuadrant.io_tlspolicies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

# Set the gateway.networking.k8s.io/policy label in the policies
patchesStrategicMerge:
  - patches/policy-patch.yaml
